sonar.projectKey=checking-front
sonar.projectName=checking front
sonar.projectVersion=1.0

# Código fuente
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Lenguajes (JS/TS)
sonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx

# Excluir cosas pesadas o irrelevantes
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**

# Tests (si tienes)
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts

# Coverage (opcional)
sonar.coverage.exclusions=**/*

# IMPORTANTE (tu caso)
sonar.host.url=http://localhost:9000
